title: "Figgy Docs"
baseurl: "/docs/"
theme: just-the-docs
color_scheme: "dark"
search_enabled: true
ga_tracking: UA-168748263-1
highlighter: none
repository: mancej/figgy.docs
plugins:
  - jekyll-seo-tag
    
exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
  - tools
  - README.md
  - .idea/