site_name: Figgy Docs
site_description: >-
  Figgy is configuration management framework designed to bring developers, DevOps engineers, and secret owners together
  around an ecosystem designed for simple and secure configuration and secret management. Figgy has features designed
  around each user story, so there's a little bit for everyone to appreciate.
site_url: https://www.figgy.dev/docs/

repo_url: https://github.com/figtools/figgy.docs
theme:
  name: material
  custom_dir: mkdocs-material/material
  language: en
  palette:
    primary: green
    accent: brown
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  features:
    - tabs
  include_sidebar: yes
  include_search_page: false
  search_index_only: true
#extra_css:
#  - stylesheets/dark-theme.css
#  - stylesheets/dark-theme-system.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/figtools
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JordanMance1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jordan-mance-78b87133/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/squidfunk
markdown_extensions:
  - toc:
      permalink: '#'
  - admonition
  - codehilite:
      guess_lang: False
#      use_pygments: True
#      noclasses: True
#      pygments_style: murphy
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - meta


nav:
  - Figgy Blog: '../'
  - Overview: 'index.md'
  - Features: 'features.md'
  - Getting Started:
    - Installing FiggyCLI: getting-started/install.md
    - Demo: getting-started/demo.md
    - Sandbox: getting-started/sandbox.md
    - Concepts: getting-started/concepts.md
    - Basics: getting-started/basics.md
  - Figgy Cloud:
      - Figgy Cloud: getting-started/deployment/select-type.md
      - Bastion: getting-started/deployment/bastion.md
      - Google: getting-started/deployment/google.md
      - Okta: getting-started/deployment/okta.md
      - Standard: getting-started/deployment/standard.md
      - Figgy Footprint: getting-started/figgy-footprint.md
  - Commands:
    - Config:
      - Get: commands/config/get.md
      - Put: commands/config/put.md
      - Delete: commands/config/delete.md
      - Edit: commands/config/edit.md
      - Browse: commands/config/browse.md
      - List: commands/config/list.md
      - Promote: commands/config/promote.md
      - Sync: commands/config/sync.md
      - Cleanup: commands/config/cleanup.md
      - Share: commands/config/share.md
      - Dump: commands/config/dump.md
      - Audit: commands/config/audit.md
      - Restore: commands/config/restore.md
      - Validate: commands/config/validate.md
    - IAM:
      - Export: commands/iam/export.md
      - Restore: commands/iam/restore.md
    - Other:
      - Configure: commands/other/configure.md
      - Version: commands/other/version.md
      - Login: commands/other/login.md
      - Upgrade: commands/other/upgrade.md
    - --flags:
      - --env: commands/flags/env.md
      - --role: commands/flags/role.md
      - --profile: commands/flags/profile.md
  - User Guides:
    - How To:
      - Manage Application Configs: user-guides/how-to/manage-application-configs.md
      - Configure CICD Validation: user-guides/how-to/cicd-validation.md
      - Manage & Share Secrets: user-guides/how-to/share-secrets.md
      - Rotate Secrets: user-guides/how-to/secret-rotation.md
    - Advanced Figgy:
      - Config Confidentiality: advanced/confidentiality.md
      - Declarative Configuration: advanced/declarative-configuration.md
      - IAM Cookbook: advanced/iam-cookbook.md
    - Developer Guide: user-guides/dev.md
    - DevOps Guide: user-guides/devops.md
    - Secret Owner Guide: user-guides/secret.md
  - Architecture:
    - Figgy Ecosystem: architecture/ecosystem.md
    - Authentication: architecture/authentication.md
    - Events: architecture/events.md
    - Security: architecture/security.md
    - Caching: architecture/caching.md
  - FAQ: faq/index.md