name: 'Continuous Integration'
on:
  push:
    branches: [master]
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - '.travis.yml'
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build Site
        run: |
          pip install mkdocs-material pymdown-extensions Pygments
          mkdocs build

      - name: Deploy
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install awscli
          bash scripts/deploy.sh
