name: 'Continuous Integration'
on:
  push:
    branches: [master]
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - '.travis.yml'
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bundle Caching
        id: bundle-cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle config
        run: |
          gem install bundler -v 2.1.4
          bundle config path vendor/bundle

      - name: Bundle Install
        if: steps.bundle-cache.outputs.cache-hit != 'true'
        run: |
          bundle install

      - name: Bundle Install locally
        if: steps.bundle-cache.outputs.cache-hit == 'true'
        run: |
          bundle install --local

      - name: Build Site
        run: |
          bash tools/build.sh

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Deploy
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install awscli
          bash tools/deploy.sh
